//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckDatabaseFromEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using KmiEntities;

    public partial class WorkdayContext : DbContext
    {

        //   : base("Data Source=DESKTOP-C0FBNF9\\SQLEXPRESS;Initial Catalog=Workday;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework")

        public WorkdayContext()
          //  : base(@"Data Source=DESKTOP-C0FBNF9\SQLEXPRESS;Initial Catalog=Workday;Integrated Security=True;")

           : base("name=WorkdayEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
            // this.Database.Connection.Open();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
             
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<User> Users { get; set; }

        public virtual DbSet<LoginUser> LoginUser { get; set; }

    }
}
