#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVCRazerEngin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<MVCRazerEngin.Models.Employee>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Employees";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2> Employee Data </h2>\r\n  Employee ID : <input");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 141), Tuple.Create("\"", 158)
            
            #line 7 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 149), Tuple.Create<System.Object, System.Int32>(Model.id
            
            #line default
            #line hidden
, 149), false)
);

WriteLiteral("></input> </br></br>\r\n  Employee Name :  <input");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 218), Tuple.Create("\"", 237)
            
            #line 8 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 226), Tuple.Create<System.Object, System.Int32>(Model.name
            
            #line default
            #line hidden
, 226), false)
);

WriteLiteral("></input> </br></br>\r\n  Employee Salary :  <input");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 299), Tuple.Create("\"", 320)
            
            #line 9 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 307), Tuple.Create<System.Object, System.Int32>(Model.salary
            
            #line default
            #line hidden
, 307), false)
);

WriteLiteral("></input> </br></br>\r\n\r\n");

            
            #line 11 "..\..\Views\Home\Index.cshtml"
Write(Html.TextBox("Name", "Aniket"));

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n");

            
            #line 13 "..\..\Views\Home\Index.cshtml"
Write(Html.TextBoxFor(x => x.salary));

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n");

WriteLiteral("\r\n\r\n\r\n<a");

WriteAttribute("href", Tuple.Create(" href=\"", 449), Tuple.Create("\"", 469)
, Tuple.Create(Tuple.Create("", 456), Tuple.Create<System.Object, System.Int32>(Href("~/Views/Home/")
, 456), false)
);

WriteLiteral("></a>\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
