//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckDatabaseFromEF
{

     
  
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;

    [ DataContract]
    [Table("User")]
    public partial class User
    {
        [DataMember]
        [Key]
        public int Id { get; set; }


       
        [DataMember]
        [Required]
        public string FirstName { get; set; }


        [DataMember]
        [MinLength(3)]
        [StringLength(40)] 
        public string LastName { get; set; }


        [DataMember]
        public Nullable<decimal> Age { get; set; }


        [DataMember]
        [ForeignKey("Department")]
        public Nullable<int> Dept_Id { get; set; }

        [DataMember]
        public string Gender { get; set; }


        [DataMember]
        public virtual Department Department { get; set; }

      


    }
}
