#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Demo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"page-heading\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"page-title\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-12 col-md-6 order-md-1 order-last\"");

WriteLiteral(">\r\n                <h3>DataTable</h3>\r\n                <p");

WriteLiteral(" class=\"text-subtitle text-muted\"");

WriteLiteral(">For user to check they list</p>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-12 col-md-6 order-md-2 order-first\"");

WriteLiteral(">\r\n                <nav");

WriteLiteral(" aria-label=\"breadcrumb\"");

WriteLiteral(" class=\"breadcrumb-header float-start float-lg-end\"");

WriteLiteral(">\r\n                    <ol");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" class=\"breadcrumb-item\"");

WriteLiteral("><a");

WriteLiteral(" href=\"index.html\"");

WriteLiteral(">Dashboard</a></li>\r\n                        <li");

WriteLiteral(" class=\"breadcrumb-item active\"");

WriteLiteral(" aria-current=\"page\"");

WriteLiteral(">DataTable</li>\r\n                    </ol>\r\n                </nav>\r\n            <" +
"/div>\r\n        </div>\r\n    </div>\r\n    <section");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"card\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"card-header\"");

WriteLiteral(">\r\n                Simple Datatable\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"card-body\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(" id=\"table1\"");

WriteLiteral(@">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>City</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Graiden</td>
                            <td>vehicula.aliquet@semconsequat.co.uk</td>
                            <td>076 4820 8838</td>
                            <td>Offenburg</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Dale</td>
                            <td>fringilla.euismod.enim@quam.ca</td>
                            <td>0500 527693</td>
                            <td>New Quay</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Nathaniel</td>
                            <td>mi.Duis@diam.edu</td>
                            <td>(012165) 76278</td>
                            <td>Grumo Appula</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-danger\"");

WriteLiteral(@">Inactive</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Darius</td>
                            <td>velit@nec.com</td>
                            <td>0309 690 7871</td>
                            <td>Ways</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Oleg</td>
                            <td>rhoncus.id@Aliquamauctorvelit.net</td>
                            <td>0500 441046</td>
                            <td>Rossignol</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Kermit</td>
                            <td>diam.Sed.diam@anteVivamusnon.org</td>
                            <td>(01653) 27844</td>
                            <td>Patna</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Jermaine</td>
                            <td>sodales@nuncsit.org</td>
                            <td>0800 528324</td>
                            <td>Mold</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Ferdinand</td>
                            <td>gravida.molestie@tinciduntadipiscing.org</td>
                            <td>(016977) 4107</td>
                            <td>Marlborough</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-danger\"");

WriteLiteral(@">Inactive</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Kuame</td>
                            <td>Quisque.purus@mauris.org</td>
                            <td>(0151) 561 8896</td>
                            <td>Tresigallo</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Deacon</td>
                            <td>Duis.a.mi@sociisnatoquepenatibus.com</td>
                            <td>07740 599321</td>
                            <td>Karapınar</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Channing</td>
                            <td>tempor.bibendum.Donec@ornarelectusante.ca</td>
                            <td>0845 46 49</td>
                            <td>Warrnambool</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Aladdin</td>
                            <td>sem.ut@pellentesqueafacilisis.ca</td>
                            <td>0800 1111</td>
                            <td>Bothey</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Cruz</td>
                            <td>non@quisturpisvitae.ca</td>
                            <td>07624 944915</td>
                            <td>Shikarpur</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Keegan</td>
                            <td>molestie.dapibus@condimentumDonecat.edu</td>
                            <td>0800 200103</td>
                            <td>Assen</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Ray</td>
                            <td>placerat.eget@sagittislobortis.edu</td>
                            <td>(0112) 896 6829</td>
                            <td>Hofors</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Maxwell</td>
                            <td>diam@dapibus.org</td>
                            <td>0334 836 4028</td>
                            <td>Thane</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Carter</td>
                            <td>urna.justo.faucibus@orci.com</td>
                            <td>07079 826350</td>
                            <td>Biez</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Stone</td>
                            <td>velit.Aliquam.nisl@sitametrisus.com</td>
                            <td>0800 1111</td>
                            <td>Olivar</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Berk</td>
                            <td>fringilla.porttitor.vulputate@taciti.edu</td>
                            <td>(0101) 043 2822</td>
                            <td>Sanquhar</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Philip</td>
                            <td>turpis@euenimEtiam.org</td>
                            <td>0500 571108</td>
                            <td>Okara</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Kibo</td>
                            <td>feugiat@urnajustofaucibus.co.uk</td>
                            <td>07624 682306</td>
                            <td>La Cisterna</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Bruno</td>
                            <td>elit.Etiam.laoreet@luctuslobortisClass.edu</td>
                            <td>07624 869434</td>
                            <td>Rocca d""Arce</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Leonard</td>
                            <td>blandit.enim.consequat@mollislectuspede.net</td>
                            <td>0800 1111</td>
                            <td>Lobbes</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Hamilton</td>
                            <td>mauris@diam.org</td>
                            <td>0800 256 8788</td>
                            <td>Sanzeno</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Harding</td>
                            <td>Lorem.ipsum.dolor@etnetuset.com</td>
                            <td>0800 1111</td>
                            <td>Obaix</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(@">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Emmanuel</td>
                            <td>eget.lacus.Mauris@feugiatSednec.org</td>
                            <td>(016977) 8208</td>
                            <td>Saint-Remy-Geest</td>
                            <td>
                                <span");

WriteLiteral(" class=\"badge bg-success\"");

WriteLiteral(">Active</span>\r\n                            </td>\r\n                        </tr>\r" +
"\n                    </tbody>\r\n                </table>\r\n            </div>\r\n   " +
"     </div>\r\n\r\n    </section>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
