#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVCRazerEngin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<html>\r\n<head>\r\n    <title></title>\r\n    <script></script>\r\n</head>\r\n<body>\r\n    " +
"<p><h2>Index</h2></p>\r\n    ");

WriteLiteral("\r\n    <table>\r\n");

            
            #line 10 "..\..\Views\Home\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Home\Index.cshtml"
         for (int i = 0; i <= 5; i++)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td");

WriteAttribute("class", Tuple.Create(" class=\"", 217), Tuple.Create("\"", 243)
            
            #line 13 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 225), Tuple.Create<System.Object, System.Int32>(i==0?"a1":"a2" 
            
            #line default
            #line hidden
, 225), false)
);

WriteLiteral(">");

            
            #line 13 "..\..\Views\Home\Index.cshtml"
                                          Write(i);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n");

WriteLiteral("            <tr>\r\n                <td>");

            
            #line 16 "..\..\Views\Home\Index.cshtml"
                Write(i + 1);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n");

            
            #line 18 "..\..\Views\Home\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </table>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
